---
# tasks file for rspamd
- name: Add rspamd official repo
  template:
    src: 'etc/rspamd.list.j2'
    dest: '/etc/apt/sources.list.d/rspamd.list'
    owner: 'root'
    group: 'root'
    mode: '0664'

- name: Add Rspamd repo key
  apt_key: 
    url: https://rspamd.com/apt-stable/gpg.key
    state: present
    validate_certs: yes

- name: Ensure rspamd is installed
  apt:
    name: '{{ item }}'
    state: 'present'
    install_recommends: 'no'
    update_cache: yes
  with_items: rspamd_packages

- name: Make sure required directories exist
  file:
    path: '{{ item }}'
    state: 'directory'
    owner: 'root'
    group: 'adm'
    mode: '2750'
  with_items: [ '/etc/rspamd' ]

- name: Configure main rmilter config file
  template:
    src: 'etc/rmilter.conf.j2'
    dest: '/etc/rmilter.conf'
    owner: 'root'
    group: '_rmilter'
    mode: '0664'
  notify: [ 'Restart rmilter' ]
